apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base
  - namespace.yaml

namePrefix: prod-
nameSuffix: -v1

replicas:
  - name: nginx-deployment
    count: 3

labels:
  - pairs:
      environment: prod
    includeTemplates: true
    includeSelectors: true

components:
  - ../../components/monitoring

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/1/resources/limits/cpu
        value: "1000m"
      - op: replace
        path: /spec/template/spec/containers/1/resources/limits/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/1/resources/requests/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/1/resources/requests/memory
        value: "256Mi"
    target:
      kind: Deployment
      name: nginx-deployment

configMapGenerator:
  - name: config
    envs:
      - prod.env

secretGenerator:
  - name: db
    envs:
    - prod-db.env