apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: debug
    envs:
      - dev.env

commonAnnotations:
  debug: "true"

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: not-used
      spec:
        template:
          spec:
            containers:
            - name: nginx
              envFrom:
              - configMapRef:
                  name: debug
              - configMapRef:
                  name: config
              - secretRef:
                  name: db
    target:
      kind: Deployment
      name: nginx-deployment